# Generated by Django 2.2.7 on 2019-11-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=400, verbose_name='Descrição')),
                ('destaque', models.CharField(help_text='Frase que ficará em destaque, podendo ser ou não uma frase da descrição', max_length=100, verbose_name='Frase em destaque')),
                ('imagem', models.ImageField(upload_to='quemSomos/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Quem Somos',
            },
        ),
        migrations.CreateModel(
            name='Relatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(help_text='Insira uma breve descrição sobre a pessoa do relato.', max_length=100, verbose_name='Texto curto')),
                ('story', models.TextField(max_length=400, verbose_name='Relato')),
                ('image', models.ImageField(blank=True, null=True, upload_to='relatos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'ordering': ['name'],
            },
        ),
    ]
