# Generated by Django 2.2.7 on 2019-11-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira o seu nome aqui.', max_length=65, verbose_name='Nome')),
                ('description', models.CharField(help_text='Insira uma breve descrição sobre você.', max_length=100, verbose_name='Texto curto')),
                ('story', models.TextField(help_text='Insira seu relato aqui.', max_length=400, verbose_name='Relato')),
                ('image', models.ImageField(blank=True, help_text='Insira uma imagem sobre a pessoa.', null=True, upload_to='relatos/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'ordering': ['name'],
            },
        ),
    ]
