
# Generated by Django 2.2.7 on 2019-11-15 14:59


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
               name='QuemSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('descricao', models.TextField(max_length=400, verbose_name='Descrição')),
                ('imagem', models.ImageField(null=True, upload_to='quemSomos/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'QuemSomos',
            },
        ),
    ]
